name: Test Custom Action

on: [push]

jobs:
  with-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Custom Setup
        uses: ./.github/actions/setup-env

      - name: Run Unit Tests
        run: npm test
